In [1]:
import pandas as pd
confirmedGlobal=pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv',encoding='utf-8',na_values=None)
df=confirmedGlobal[confirmedGlobal['Country/Region']=='India'].transpose().iloc[4:].reset_index()
df.columns=['Dates','Cumulated Values']
df['Actual Values']=df['Cumulated Values'] -df['Cumulated Values'].shift(1).fillna(0)

In [2]:
df.head()

     Dates Cumulated Values Actual Values
0  1/22/20                0             0
1  1/23/20                0             0
2  1/24/20                0             0
3  1/25/20                0             0
4  1/26/20                0             0

In [11]:
allData=[]
for i in range(df.shape[0]):
    temp=df.iloc[i]
    allData.append(dict(temp))

In [12]:
allData

[{'Dates': '1/22/20', 'Cumulated Values': 0, 'Actual Values': 0},
 {'Dates': '1/23/20', 'Cumulated Values': 0, 'Actual Values': 0},
 {'Dates': '1/24/20', 'Cumulated Values': 0, 'Actual Values': 0},
 {'Dates': '1/25/20', 'Cumulated Values': 0, 'Actual Values': 0},
 {'Dates': '1/26/20', 'Cumulated Values': 0, 'Actual Values': 0},
 {'Dates': '1/27/20', 'Cumulated Values': 0, 'Actual Values': 0},
 {'Dates': '1/28/20', 'Cumulated Values': 0, 'Actual Values': 0},
 {'Dates': '1/29/20', 'Cumulated Values': 0, 'Actual Values': 0},
 {'Dates': '1/30/20', 'Cumulated Values': 1, 'Actual Values': 1},
 {'Dates': '1/31/20', 'Cumulated Values': 1, 'Actual Values': 0},
 {'Dates': '2/1/20', 'Cumulated Values': 1, 'Actual Values': 0},
 {'Dates': '2/2/20', 'Cumulated Values': 2, 'Actual Values': 1},
 {'Dates': '2/3/20', 'Cumulated Values': 3, 'Actual Values': 1},
 {'Dates': '2/4/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/5/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/6/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/7/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/8/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/9/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/10/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/11/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/12/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/13/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/14/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/15/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/16/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/17/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/18/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/19/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/20/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/21/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/22/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/23/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/24/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/25/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/26/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/27/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/28/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '2/29/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '3/1/20', 'Cumulated Values': 3, 'Actual Values': 0},
 {'Dates': '3/2/20', 'Cumulated Values': 5, 'Actual Values': 2},
 {'Dates': '3/3/20', 'Cumulated Values': 5, 'Actual Values': 0},
 {'Dates': '3/4/20', 'Cumulated Values': 28, 'Actual Values': 23},
 {'Dates': '3/5/20', 'Cumulated Values': 30, 'Actual Values': 2},
 {'Dates': '3/6/20', 'Cumulated Values': 31, 'Actual Values': 1},
 {'Dates': '3/7/20', 'Cumulated Values': 34, 'Actual Values': 3},
 {'Dates': '3/8/20', 'Cumulated Values': 39, 'Actual Values': 5},
 {'Dates': '3/9/20', 'Cumulated Values': 43, 'Actual Values': 4},
 {'Dates': '3/10/20', 'Cumulated Values': 56, 'Actual Values': 13},
 {'Dates': '3/11/20', 'Cumulated Values': 62, 'Actual Values': 6},
 {'Dates': '3/12/20', 'Cumulated Values': 73, 'Actual Values': 11},
 {'Dates': '3/13/20', 'Cumulated Values': 82, 'Actual Values': 9},
 {'Dates': '3/14/20', 'Cumulated Values': 102, 'Actual Values': 20},
 {'Dates': '3/15/20', 'Cumulated Values': 113, 'Actual Values': 11},
 {'Dates': '3/16/20', 'Cumulated Values': 119, 'Actual Values': 6},
 {'Dates': '3/17/20', 'Cumulated Values': 142, 'Actual Values': 23},
 {'Dates': '3/18/20', 'Cumulated Values': 156, 'Actual Values': 14},
 {'Dates': '3/19/20', 'Cumulated Values': 194, 'Actual Values': 38},
 {'Dates': '3/20/20', 'Cumulated Values': 244, 'Actual Values': 50},
 {'Dates': '3/21/20', 'Cumulated Values': 330, 'Actual Values': 86},
 {'Dates': '3/22/20', 'Cumulated Values': 396, 'Actual Values': 66},
 {'Dates': '3/23/20', 'Cumulated Values': 499, 'Actual Values': 103},
 {'Dates': '3/24/20', 'Cumulated Values': 536, 'Actual Values': 37},
 {'Dates': '3/25/20', 'Cumulated Values': 657, 'Actual Values': 121},
 {'Dates': '3/26/20', 'Cumulated Values': 727, 'Actual Values': 70},
 {'Dates': '3/27/20', 'Cumulated Values': 887, 'Actual Values': 160},
 {'Dates': '3/28/20', 'Cumulated Values': 987, 'Actual Values': 100},
 {'Dates': '3/29/20', 'Cumulated Values': 1024, 'Actual Values': 37},
 {'Dates': '3/30/20', 'Cumulated Values': 1251, 'Actual Values': 227},
 {'Dates': '3/31/20', 'Cumulated Values': 1397, 'Actual Values': 146},
 {'Dates': '4/1/20', 'Cumulated Values': 1998, 'Actual Values': 601},
 {'Dates': '4/2/20', 'Cumulated Values': 2543, 'Actual Values': 545},
 {'Dates': '4/3/20', 'Cumulated Values': 2567, 'Actual Values': 24},
 {'Dates': '4/4/20', 'Cumulated Values': 3082, 'Actual Values': 515},
 {'Dates': '4/5/20', 'Cumulated Values': 3588, 'Actual Values': 506},
 {'Dates': '4/6/20', 'Cumulated Values': 4778, 'Actual Values': 1190},
 {'Dates': '4/7/20', 'Cumulated Values': 5311, 'Actual Values': 533},
 {'Dates': '4/8/20', 'Cumulated Values': 5916, 'Actual Values': 605},
 {'Dates': '4/9/20', 'Cumulated Values': 6725, 'Actual Values': 809},
 {'Dates': '4/10/20', 'Cumulated Values': 7598, 'Actual Values': 873},
 {'Dates': '4/11/20', 'Cumulated Values': 8446, 'Actual Values': 848},
 {'Dates': '4/12/20', 'Cumulated Values': 9205, 'Actual Values': 759},
 {'Dates': '4/13/20', 'Cumulated Values': 10453, 'Actual Values': 1248},
 {'Dates': '4/14/20', 'Cumulated Values': 11487, 'Actual Values': 1034},
 {'Dates': '4/15/20', 'Cumulated Values': 12322, 'Actual Values': 835},
 {'Dates': '4/16/20', 'Cumulated Values': 13430, 'Actual Values': 1108},
 {'Dates': '4/17/20', 'Cumulated Values': 14352, 'Actual Values': 922},
 {'Dates': '4/18/20', 'Cumulated Values': 15722, 'Actual Values': 1370},
 {'Dates': '4/19/20', 'Cumulated Values': 17615, 'Actual Values': 1893},
 {'Dates': '4/20/20', 'Cumulated Values': 18539, 'Actual Values': 924},
 {'Dates': '4/21/20', 'Cumulated Values': 20080, 'Actual Values': 1541},
 {'Dates': '4/22/20', 'Cumulated Values': 21370, 'Actual Values': 1290},
 {'Dates': '4/23/20', 'Cumulated Values': 23077, 'Actual Values': 1707},
 {'Dates': '4/24/20', 'Cumulated Values': 24530, 'Actual Values': 1453},
 {'Dates': '4/25/20', 'Cumulated Values': 26283, 'Actual Values': 1753},
 {'Dates': '4/26/20', 'Cumulated Values': 27890, 'Actual Values': 1607},
 {'Dates': '4/27/20', 'Cumulated Values': 29451, 'Actual Values': 1561},
 {'Dates': '4/28/20', 'Cumulated Values': 31324, 'Actual Values': 1873},
 {'Dates': '4/29/20', 'Cumulated Values': 33062, 'Actual Values': 1738},
 {'Dates': '4/30/20', 'Cumulated Values': 34863, 'Actual Values': 1801},
 {'Dates': '5/1/20', 'Cumulated Values': 37257, 'Actual Values': 2394},
 {'Dates': '5/2/20', 'Cumulated Values': 39699, 'Actual Values': 2442}]